apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
  namespace: argocd
spec:
  destination:
    namespace: dna
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /deploy
    repoURL: https://github.com/ryane/sampleapp.git
