apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: sampleapp
    component: api
    release: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
      component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampleapp
        component: api
        release: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sampleapp
                  component: api
                  release: v1
              topologyKey: kubernetes.io/hostname
            weight: 100
      volumes:
      - name: config
        configMap:
          name: config
      containers:
      - name: http
        image: ryane/sampleapp:kubecon
        imagePullPolicy: Always
        command: []
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
          subPath: 
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9080
          protocol: TCP
