apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: sampleapp
    component: api
    release: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
      component: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sampleapp
        component: api
        release: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sampleapp
                  component: api
                  release: v1
              topologyKey: kubernetes.io/hostname
            weight: 100
      volumes:
      - name: ca-bundles
        configMap:
          name: ca-bundles
      - name: data
        persistentVolumeClaim:
          claimName: data
      containers:
      - name: api
        image: nginx:latest
        imagePullPolicy: Always
        command: []
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-bundles
          readOnly: true
        - mountPath: /data
          name: data
          readOnly: true
          subPath: []
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
