apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sampleapp
    release: v1
  name: data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: SSD
