apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sampleapp
    release: v1
  name: datavol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard
