apiVersion: v1
kind: Service
metadata:
  labels:
    component: api
    app: sampleapp
    release: v1
  name: api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: sampleapp
    component: sampleapp
  type: ClusterIP
